// Copyright 2026 m1rwana12. All rights reserved.  Use of this source code is
// governed by the MIT license that can be found in the LICENSE file.

// Package screenshot turns the contents of a tcell simulation screen into
// something that can be committed to the repository: plain text for tests to
// compare against, and SVG for the documentation.
//
// The point is that both come from the same run. A picture in the README that
// is regenerated by the same command a test asserts on cannot quietly drift
// away from what the program does.
package screenshot

import (
	"fmt"
	"strings"

	"github.com/gdamore/tcell/v2"
)

//======================================================================

// Cell is one character on the screen with the styling it was drawn in.
type Cell struct {
	Rune  rune
	Style tcell.Style
}

// Grab reads the whole screen. Trailing blanks on each line are kept, because
// a line that is blank to the right edge and one that is short are different
// screens, and a golden file should notice.
func Grab(s tcell.SimulationScreen) ([][]Cell, int, int) {
	raw, w, h := s.GetContents()

	rows := make([][]Cell, h)
	for y := 0; y < h; y++ {
		row := make([]Cell, w)
		for x := 0; x < w; x++ {
			c := raw[y*w+x]
			r := ' '
			if len(c.Runes) > 0 && c.Runes[0] != 0 {
				r = c.Runes[0]
			}
			row[x] = Cell{Rune: r, Style: c.Style}
		}
		rows[y] = row
	}

	return rows, w, h
}

// Text renders the screen as plain text, one line per row, right-trimmed.
//
// This is what the tests compare. Style is deliberately dropped: a golden file
// that encodes colour would fail on every palette tweak, and the thing worth
// catching is a pane that stopped being drawn, not a shade that changed.
func Text(rows [][]Cell) string {
	var b strings.Builder

	for _, row := range rows {
		var line strings.Builder
		for _, c := range row {
			line.WriteRune(c.Rune)
		}
		b.WriteString(strings.TrimRight(line.String(), " "))
		b.WriteByte('\n')
	}

	return b.String()
}

//======================================================================

// Geometry of the rendered SVG, in pixels. Chosen so the character cell is
// close to a real terminal's at a readable size.
const (
	cellW   = 8.4
	cellH   = 18.0
	padding = 16.0
)

// SVG renders the screen as an image for the documentation.
//
// Cells are emitted in runs of identical style rather than one element each: a
// 120x36 screen is over four thousand cells, and one element per cell produces
// a file too large to review in a diff.
func SVG(rows [][]Cell, w, h int) string {
	width := float64(w)*cellW + padding*2
	height := float64(h)*cellH + padding*2

	var b strings.Builder

	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f" width="%.0f" height="%.0f" role="img">`,
		width, height, width, height)
	b.WriteByte('\n')
	fmt.Fprintf(&b, `  <rect width="%.0f" height="%.0f" rx="10" fill="%s"/>`+"\n", width, height, defaultBg)
	fmt.Fprintf(&b, `  <g font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace" font-size="14">`)
	b.WriteByte('\n')

	// Backgrounds first, so text is never painted under a later rectangle.
	for y, row := range rows {
		for _, run := range runs(row) {
			bg := background(run.style)
			if bg == defaultBg {
				continue
			}
			fmt.Fprintf(&b, `    <rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="%s"/>`+"\n",
				padding+float64(run.from)*cellW, padding+float64(y)*cellH,
				float64(run.to-run.from+1)*cellW, cellH, bg)
		}
	}

	for y, row := range rows {
		for _, run := range runs(row) {
			text := strings.TrimRight(run.text, " ")
			if text == "" {
				continue
			}
			fmt.Fprintf(&b, `    <text x="%.2f" y="%.2f" fill="%s"%s xml:space="preserve">%s</text>`+"\n",
				padding+float64(run.from)*cellW, padding+float64(y)*cellH+cellH*0.72,
				foreground(run.style), weight(run.style), escape(text))
		}
	}

	b.WriteString("  </g>\n</svg>\n")
	return b.String()
}

//======================================================================

type run struct {
	from, to int
	style    tcell.Style
	text     string
}

func runs(row []Cell) []run {
	var res []run

	for i := 0; i < len(row); {
		j := i
		var sb strings.Builder
		for j < len(row) && row[j].Style == row[i].Style {
			sb.WriteRune(row[j].Rune)
			j++
		}
		res = append(res, run{from: i, to: j - 1, style: row[i].Style, text: sb.String()})
		i = j
	}

	return res
}

// The palette from docs/Brand.md, used when a cell asks for the terminal's
// default rather than a specific colour.
const (
	defaultBg = "#0D1117"
	defaultFg = "#E6EDF3"
)

func foreground(s tcell.Style) string {
	fg, _, _ := s.Decompose()
	return hex(fg, defaultFg)
}

func background(s tcell.Style) string {
	_, bg, _ := s.Decompose()
	return hex(bg, defaultBg)
}

func weight(s tcell.Style) string {
	if _, _, attr := s.Decompose(); attr&tcell.AttrBold != 0 {
		return ` font-weight="700"`
	}
	return ""
}

func hex(c tcell.Color, fallback string) string {
	if c == tcell.ColorDefault {
		return fallback
	}
	if !c.Valid() {
		return fallback
	}
	r, g, b := c.RGB()
	if r < 0 || g < 0 || b < 0 {
		return fallback
	}
	return fmt.Sprintf("#%02X%02X%02X", r, g, b)
}

func escape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	return r.Replace(s)
}

//======================================================================
// Local Variables:
// mode: Go
// fill-column: 78
// End:
